### PR TITLE
bump to Java 11, Payara-5.2021.2

### PR DESCRIPTION
**Pull request by donsizemore**
and don't enable-secure-admin, which throws protocol errors

### CODE REVIEW

**Comment by akio-sone** [comment]
Don, I'm OK with your revisions; one thing I'd like to confirm is that after these changes, does the payara server still write log lines such as those related to the deployment of trsa's war file to the sever.log?  When I tested payara-full-server's official docker images (both java8/11-based ones), the factory default was not logging.  Their base images are so thin that even vi was not included (path issue?), I could not edit the logging.properties file and had to use an asadmin subcommand to enable usual logging.

**Comment by donsizemore** [comment]
I just ran the Docker image, which logged:

```
[2021-04-22T18:27:34.591+0000] [Payara 5.2021.2] [INFO] [AS-WEB-GLUE-00172] [javax.enterprise.web] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1619116054591] [levelValue: 800] [[
  Loading application [trsa-web-2.0] at [/trsa-web-2.0]]]

[2021-04-22T18:27:34.976+0000] [Payara 5.2021.2] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1619116054976] [levelValue: 800] [[
  trsa-web-2.0 was successfully deployed in 18,592 milliseconds.]]

[2021-04-22T18:27:34.980+0000] [Payara 5.2021.2] [INFO] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1619116054980] [levelValue: 800] [[
  Boot Command deploy returned with result SUCCESS : PlainTextActionReporterSUCCESSDescription: deploy AdminCommandApplication deployed with name trsa-web-2.0.
    [name=trsa-web-2.0]]
```

If you want a higher verbosity, could you send me the asadmin command you'd like used?

**Comment by akio-sone** [comment]
Don, this is what I was expecting by default; for these official images, their default is not logging into sever.log.  Thanks. So I am going to accept this PR; are you OK now?

**Review by akio-sone — COMMENTED** [review]
These updates are accepted.

**Pull request merged**
